name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  talker: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_flutter: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/